apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: j7dcp868t-python 
  janus-idp.io/tekton: j7dcp868t-python
  backstage.io/kubernetes-id: j7dcp868t-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: j7dcp868t-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml